### ISSUE TITLE
A little different from the paper

### ISSUE THREAD

**Issue by hityzy1122** [LabForComputationalVision/universal_inverse_problem#1]
Hi
thanks for your code, but there are a few differences between this code and paper.
(1) y = y -  h*d + gamma*noise in code is written as  y = y +  h*d + gamma*noise in paper
(2) d = f_y - M(M_T(f_y[0])) + ( M(M_T(y[0]))  - M(x_c) ) in code is written as d = f_y - M(M_T(f_y[0])) + (M(x_c) - M(M_T(y[0]))) in paper
I wonder which is a clerical error.
Thanks!

**Comment by eerosim** [comment]
Dear Ocean,

The math in the paper should be correct.

(1) The sign of the second term should be consistent with the definition of d.  If d = hat{x}(y) - y = f(y), then the sign should be positive.

(2) With the constraint [ M^Tx = x_c ],  the adjustment should be  d = [ I - MM^T ] f(y)  +  M [ x_c - M^T y ]

**Comment by YU-Zhiyang** [comment]
> Dear Ocean, The math in the paper should be correct. (1) The sign of the second term should be consistent with the definition of d. If d = hat{x}(y) - y = f(y), then the sign should be positive. (2) With the constraint [ M^Tx = x_c ], the adjustment should be d = [ I - MM^T ] f(y) + M [ x_c - M^T y ]
> […](#)
> On Nov 7, 2021, at 9:22 AM, Ocean YU ***@***.***> wrote: Hi thanks for your code, but there are a few differences between this code and paper. (1) y = y - hd + gammanoise in code is written as y = y + hd + gammanoise in paper (2) d = f_y - M(M_T(f_y[0])) + ( M(M_T(y[0])) - M(x_c) ) in code is written as d = f_y - M(M_T(f_y[0])) + (M(x_c) - M(M_T(y[0]))) in paper I wonder which is a clerical error. Thanks! — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_LabForComputationalVision_universal-5Finverse-5Fproblem_issues_1&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=2OT5_l3D87R1erckhEd5F5VQXs8_HiQmVADWPviXEjU&m=pbn896zEnp6FkmpVLNx4e3HUPPGZVfi9vVX8La1cIX8C9gTHkq8R0ci5nYhibMY0&s=rxdMI563APPo8npZWNp4vyL7XWKeVWyF2ner76Jx8B0&e=>, or unsubscribe <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AB5A4S2DQRRXOJCGYVPMDRDUK2DSRANCNFSM5HQ34GTQ&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=2OT5_l3D87R1erckhEd5F5VQXs8_HiQmVADWPviXEjU&m=pbn896zEnp6FkmpVLNx4e3HUPPGZVfi9vVX8La1cIX8C9gTHkq8R0ci5nYhibMY0&s=lH8FHHQCIFR8mZMrTYRkXgGu2R8dHH0QgoGcb_S_l3s&e=>. Triage notifications on the go with GitHub Mobile for iOS <https://urldefense.proofpoint.com/v2/url?u=https-3A__apps.apple.com_app_apple-2Dstore_id1477376905-3Fct-3Dnotification-2Demail-26mt-3D8-26pt-3D524675&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=2OT5_l3D87R1erckhEd5F5VQXs8_HiQmVADWPviXEjU&m=pbn896zEnp6FkmpVLNx4e3HUPPGZVfi9vVX8La1cIX8C9gTHkq8R0ci5nYhibMY0&s=QeIiM8bfVTg9GStg7kPaJ024BJgSwd83JfsAnQFcBWs&e=> or Android <https://urldefense.proofpoint.com/v2/url?u=https-3A__play.google.com_store_apps_details-3Fid-3Dcom.github.android-26referrer-3Dutm-5Fcampaign-253Dnotification-2Demail-2526utm-5Fmedium-253Demail-2526utm-5Fsource-253Dgithub&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=2OT5_l3D87R1erckhEd5F5VQXs8_HiQmVADWPviXEjU&m=pbn896zEnp6FkmpVLNx4e3HUPPGZVfi9vVX8La1cIX8C9gTHkq8R0ci5nYhibMY0&s=lFCcoowNxg8jLqA4q31g2M5HbY1PRE1QubviP5U1SNY&e=>.

Thanks for your replay, I want to know if the f_y which is the output of denoiser ( f_y = model(y) ) in code is  y-x^hat(y) in fact, if so, I think the code is agreement with the paper.

**Comment by hityzy1122** [comment]
Thanks for your replay ! I want to know if the f_y which is the output of denoiser ( f_y = model(y) ) in code is y-x^hat(y) in fact, if so, I think the code is agreement with the paper.

**Comment by eerosim** [comment]
Yes, f_y(y) =  y-x^hat(y), the denoiser “residual”.

Best,
Eero

**Comment by hityzy1122** [comment]
Thanks!
